set(_CATKIN_CURRENT_PACKAGE "abd")
set(abd_VERSION "0.0.0")
set(abd_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(abd_PACKAGE_FORMAT "1")
set(abd_BUILD_DEPENDS "message_generation" "roscpp" "sensor_msgs" "std_msgs")
set(abd_BUILD_EXPORT_DEPENDS "message_runtime" "roscpp" "sensor_msgs" "std_msgs")
set(abd_BUILDTOOL_DEPENDS "catkin")
set(abd_BUILDTOOL_EXPORT_DEPENDS )
set(abd_EXEC_DEPENDS "message_runtime" "roscpp" "sensor_msgs" "std_msgs")
set(abd_RUN_DEPENDS "message_runtime" "roscpp" "sensor_msgs" "std_msgs")
set(abd_TEST_DEPENDS )
set(abd_DOC_DEPENDS )
set(abd_DEPRECATED "")